spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432}/auth_db
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
springdoc:
  swagger-ui:
    operations-sorter: method
application:
  security:
    secretKey: 3292a479c01428d3f4d9129f46d4165a809452ec4a7359e889e14d84d648ae23c5f6b7e8b395572ba4b697f2e9167dab
    jwt-expiration: 36000000
    refresh-expiration: 36000000
server:
  port: 8063
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.security: DEBUG
