spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/categories/**
        - id: product-variant-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product-variants/**

server:
  port: 8222