spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432}/product_db
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:http://localhost9092}
springdoc:
  swagger-ui:
    operations-sorter: method

application:
  config:
    category-service:
      name: category-service
      url: ${APPLICATION_CONFIG_CATEGORY_SERVICE_URL:http://localhost:8060}/api/v1/categories

server:
  port: 8070
  servlet:
    context-path: /api/v1
eureka:
  client:
    enabled: false